keyboards_ecommerce/views.py
from sys import path_hooks
from xml.etree.ElementTree import Comment
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from datetime import datetime
from . import db
from .forms import CheckoutForm
from sqlalchemy import or_

from keyboards_ecommerce.models import Category, Keyboard, Order

bp = Blueprint('main', __name__)

# top page


@bp.route('/')
def index():
    keyboards = Keyboard.query.order_by(Keyboard.id).all()
    categories = Category.query.order_by(Category.id).all()

    return render_template('index.html', keyboards=keyboards, categories=categories, display_type="All")

# keyboard detail page


@bp.route('/keyboards/<int:keyboardid>/')
def keyboard_detail(keyboardid):
    keyboard = Keyboard.query.get(keyboardid)
    category = Category.query.get(keyboard.category_id)

    return render_template('detail.html', keyboard=keyboard, category=category)

# search keyboard by category


@bp.route('/categories/<int:categoryid>/')
def keybord_categorised(categoryid):

    keyboards = Keyboard.query.filter(
        Keyboard.category_id == categoryid)

    selected_category = Category.query.get(categoryid)
    return render_template('category.html', keyboards=keyboards, category=selected_category)

# search keyboards by words


@bp.route('/search/', methods=['POST'])
def search():
    search_word = request.form["searchWord"]
    formated_search_word = "%{}%".format(search_word)
    # get keyboards related with search word
    keyboards = Keyboard.query.filter(or_(Keyboard.name.like(formated_search_word), Keyboard.conective.like(
        formated_search_word), Keyboard.description.like(formated_search_word)))
    categories = Category.query.order_by(Category.id).all()

    return render_template('index.html', keyboards=keyboards, categories=categories, display_type="Result by {}".format(search_word))

# order page


@bp.route('/order/', methods=['POST', 'GET'])
def order():
    keyboard_id = request.args.get('keyboard_id')

    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', lastname='',
                      email='', address='', date=datetime.now(), totalcost=0)
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None

      # calcultate totalprice
    totalprice = 0
    if order is not None:
        for keyboard in order.keyboards:
            totalprice = totalprice + keyboard.price

    # are we adding an item?
    if keyboard_id is not None and order is not None:
        keyboard = Keyboard.query.get(keyboard_id)
        if keyboard not in order.keyboards:
            try:
                order.keyboards.append(keyboard)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('This keyboard is already in basket', category='danger')
            return redirect(url_for('main.order'))

    return render_template('order.html', order=order, totalprice=totalprice)


# delete item from cart

@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        keyboard_to_delete = Keyboard.query.get(id)
        try:
            order.keyboards.remove(keyboard_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# delete all items


@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted', category="danger")
    return redirect(url_for('main.order'))

# complete order


@bp.route('/checkout/', methods=['POST', 'GET'])
def checkout():
    form = CheckoutForm()
    totalprice = 0
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        for keyboard in order.keyboards:
            totalprice = totalprice + keyboard.price

        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.lastname = form.lastname.data
            order.email = form.email.data
            order.address = form.address.data
            totalcost = 0
            for keyboard in order.keyboards:
                totalcost = totalcost + keyboard.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash(
                    'Thank you! Products will be shipped within one week!', category="primary")

                return redirect(url_for('main.complete'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form, order=order, totalprice=totalprice)

# confirm page


@bp.route('/complete/')
def complete():
    return render_template('complete.html')

keyboards_ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Fantastic Keyboards">

    <!-- Bootstrap Required Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Fantastic Keyboards</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/mystyle.css')}}">
</head>

<body>
    <div class="wrapper">
        <header id="head">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="{{url_for('main.index')}}">Fantastic Keyboards</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
                    aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <a class="nav-item text-light nav-link" href="{{url_for('main.index')}}">Home</a>
                        <div class="dropdown">
                            <a class="nav-item text-light nav-link dropdown-toggle" data-toggle="dropdown"
                                id="bookDropdown" aria-haspopup="true" aria-expanded="false" href="#">Category</a>
                            <div class="dropdown-menu" aria-labelledby="bookDropdown">
                                <a class="dropdown-item"
                                    href="{{ url_for('main.keybord_categorised', categoryid=1) }}">Gaming</a>
                                <div id="GamingNav" class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                    href="{{ url_for('main.keybord_categorised', categoryid=2) }}">Capactive</a>
                                <div id="CapactiveNav" class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                    href="{{ url_for('main.keybord_categorised', categoryid=3) }}">Pantograph</a>
                                <div id="PantographNav" class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                    href="{{ url_for('main.keybord_categorised', categoryid=4) }}">Other</a>
                                <div id="OtherNav" class="dropdown-divider"></div>
                            </div>
                        </div>

                        <form class="form-inline my-2 my-lg-0 mx-1" action="{{url_for('main.search')}}" method="post">
                            <input class="form-control mr-1" type="text" placeholder="Search" name="searchWord">
                            <button class="btn my-2 my-sm-0 header-icon-btn" type="submit">
                                <img src="{{url_for('static', filename='img/search.svg')}}" class="header-icon">
                            </button>
                        </form>
                        <li class="nav-item">
                            <a type="button" class="btn header-icon-btn" href="{{url_for('main.order')}}">
                                <img src="{{url_for('static', filename='img/cart.svg')}}" class="header-icon">
                                <span class="text-light">Cart</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </nav>

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="flashes">
                <div class="alert alert-{{category}} mb-0" role="alert">
                    {{ message }}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% endwith %}

            {% block head %}{% endblock %}
        </header>

        <div class="inner">
            <main class="container">
                {% block main %}{% endblock %}
            </main>
        </div>

        <!-- Footer of the website -->
        <footer class="footer">
            <div class="bg-secondary text-center" id="footerBackTop">
                <a class="text-white d-block" href="#head">Back to Top</a>
            </div>
            <div class="text-center py-2 bg-dark">
                <p class="text-white">Copyright &copy; 2022</p>
                <p class="text-white">Coded with by Takao Mizuno</p>
                <p class="text-white">No: N11235624</p>
                <img src="{{url_for('static', filename='img/qut.png')}}" height="120">
            </div>
        </footer>

    </div>

    <!-- JQuery -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>

</body>

</html>

keyboards_ecommerce/templates/category.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="mb-0 jumbotron jumbotron-fluid card card-image header-img">
    <div class="row justify-content-center mt-5 pb-4">
        <div class="col-md-8">
            <div class="jumbotron shadow py-4 mb-5 ">
                <h1 class="text-center">Happy Keyboards Life</h1>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<section>
    <div>
        <h1 class="border-bottom">{{category.name}}</h1>
    </div>

    <div class="row">
        {% for keyboard in keyboards%}
        <dic class="col-lg-3 mt-2">
            <a class="card h-100 card-background-color text-dark card-hover"
                href="{{ url_for('main.keyboard_detail', keyboardid=keyboard.id) }}">
                <img class="card-img-top" src="{{url_for('static', filename='img/products/'+keyboard.image)}}"
                    alt="{{keyboard.id}}">
                <div class="card-body">
                    <h3 class="card-title text-truncate">{{keyboard.name}}</h3>
                    <span class="card-text text-danger">AUD </span>
                    <span class="card-text text-danger">{{keyboard.price}}</span>
                </div>
            </a>
        </dic>
        {% endfor %}
    </div>
</section>

<section class="mt-3">
    <div>
        <h2 class="border-bottom">About {{category.name}} Keyboard</h2>
    </div>
    <p>
        {{category.description}}
    </p>

</section>
{% endblock %}

keyboards_ecommerce/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Checkout</h1>
                <p>
                    Thank you for purchasing. Please provide your details so that we can ship items for you within one
                    week. Thank you!
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="border-bottom">
                    <h5 class="font-italic">Order list</h5>
                </div>
                <ul>
                    {% for keyboard in order.keyboards %}
                    <li>
                        {{keyboard.name}}
                    </li>
                    {% endfor %}
                </ul>
                <div class="border-bottom">
                    <h5 class="font-italic">Total price</h5>
                </div>
                <span> {{ "$%.2f"|format(totalprice) }}
                </span>
            </div>
            <div class="col-lg-6 my-3">
                {{wtf.quick_form(form)}}

            </div>
        </div>
    </div>
</section>
{% endblock %}

keyboards_ecommerce/templates/complete.html
{% extends 'base.html' %}

{% block main %}
<section class="py-3">
    <div class="text-center">
        <h2>Complete your order!</h2>
    </div>
    <div class="text-center">
        <a type="button" class="btn btn-dark" href="{{url_for('main.index')}}">
            Back to Top Page
        </a>
    </div>
</section>
{% endblock%}

keyboards_ecommerce/templates/detail.html
{% extends 'base.html' %}

{% block main %}

<body>
    <main class="site-background-color">
        <div class="container">
            <section>
                <div>
                    <h1>{{keyboard.name}}</h1>
                </div>
                <div class="row">
                    <div class="col-lg-8">
                        <img src="{{url_for('static', filename='img/products/'+keyboard.image)}}" class="img-fluid">
                    </div>

                    <div class="col-lg-4">
                        <div class="border border-secondary rounded p-3">
                            <div class="mb-3">
                                <span>
                                    Price:
                                </span>
                                <h4 class="text-danger">AUD {{keyboard.price}}</h4>
                            </div>
                            <div class="text-center">
                                <a type="button" class="btn btn-dark btn-mg"
                                    href="{{url_for('main.order', keyboard_id=keyboard.id)}}">
                                    Add to Cart
                                </a>

                            </div>
                        </div>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th colspan="2">Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="font-italic">Brand</td>
                                    <td>{{keyboard.brand}}</td>
                                </tr>
                                <tr>
                                    <td class="font-italic">Price</td>
                                    <td>AUD {{keyboard.price}}</td>
                                </tr>
                                <tr>
                                    <td class="font-italic">Conective</td>
                                    <td>{{keyboard.conective}}</td>
                                </tr>
                                <tr>
                                    <td class="font-italic">Categoty</td>
                                    <td>{{category.name}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>

            <section>
                <h4>Description</h4>
                <ul>
                    {% set descriptions = keyboard.description.split(';') %}
                    {% for description in descriptions %}
                    <li>{{description}}</li>
                    {% endfor %}
                </ul>

            </section>
        </div>

    </main>


</body>

{% endblock%}


</html>

keyboards_ecommerce/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="mb-0 jumbotron jumbotron-fluid card card-image header-img">
    <div class="row justify-content-center mt-5 pb-4">
        <div class="col-md-8">
            <div class="jumbotron shadow py-4 mb-5 ">
                <h1 class="text-center">Happy Keyboards Life</h1>

            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block main %}
<section>
    <div>
        <h1 class="border-bottom">{{display_type}}</h1>
    </div>

    <div class="row">
        {% for keyboard in keyboards%}
        <dic class="col-lg-3 mt-2">
            <a class="card h-100 card-background-color text-dark card-hover"
                href="{{ url_for('main.keyboard_detail', keyboardid=keyboard.id) }}">
                <img class="card-img-top" src="{{url_for('static', filename='img/products/'+keyboard.image)}}"
                    alt="{{keyboard.id}}">
                <div class="card-body">
                    <h5 class="card-title text-truncate">{{keyboard.name}}</h5>
                    <span class="card-text text-danger">AUD </span>
                    <span class="card-text text-danger">{{keyboard.price}}</span>
                </div>
            </a>
        </dic>
        {% endfor %}
    </div>

</section>

<section class="py-3">
    <div>
        <h1 class="border-bottom">
            Category
        </h1>
    </div>

    {% for category in categories%}
    <a class="card mb-3 category-hover category-img" id="{{category.name}}Category"
        href="{{ url_for('main.keybord_categorised', categoryid=category.id) }}">
        <div class="row no-gutters">
            <div class="col-lg-12">
                <div class="card-body text-white fadeLeft">
                    <h4 class="card-title font-italic">{{category.name}}</h4>
                    <p class="card-text">{{category.description}}</p>
                    <h5 class="card-text font-italic">Click to search for {{category.name.lower()}} keyboards</h5>
                </div>
            </div>
        </div>
    </a>
    {% endfor%}

</section>
{% endblock %}



</html>

keyboards_ecommerce/templates/order.html
{% extends 'base.html' %}

{% block main %}

<section>
    <div class="py-3">
        {% if order.keyboards == [] %}
        <div class="row shadow-md mb-3">
            <div class="col-lg-12 card">
                <div class="card-body">
                    <h3>
                        No Items
                    </h3>
                </div>
            </div>
        </div>
        {% else %}
        {% for keyboard in order.keyboards %}
        <div class="row shadow-md my-3">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <a class="align-self-center order-head"
                            href="{{ url_for('main.keyboard_detail', keyboardid=keyboard.id) }}">
                            <h5 class="text-dark">{{keyboard.name}}</h5>
                        </a>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{keyboard.id}}">
                            <button class="btn btn-outline-secondary" type="submit">
                                <span class="icon icon-trash mt-1"></span>
                            </button>
                        </form>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-2">
                                <img class="img-thumbnail"
                                    src="{{url_for('static', filename=('img/products/' + keyboard.image))}}">
                            </div>
                            <div class="col-lg-7">
                                <!-- Item Description -->
                                <div>
                                    <span class="text-secondary">Brand:</span>
                                    <span>{{keyboard.brand}}</span>
                                </div>
                                <div>
                                    <span class="text-secondary">Conective:</span>
                                    <span>{{keyboard.conective}}</span>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <p class="text-secondary">Price: </p>
                                <h5>{{ "$%.2f"|format(keyboard.price) }}</h5>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="border-top">
            <h4 class="text-right text-danger">
                Total: {{ "$%.2f"|format(totalprice) }}
            </h4>
        </div>
        <div class="text-right">
            <a href="{{ url_for('main.checkout') }}" class="btn btn-dark">Proceed to
                Checkout</a>
        </div>

        <div class="text-right mt-5">
            <a href="{{ url_for('main.deleteorder') }}" class="btn btn-secondary">Delete All Items</a>
        </div>

        {% endif %}

    </div>



</section>
{% endblock%}